- name: Hello World Sample
  hosts: all
  tasks:
    - name: Get filebeat status
      shell: systemctl status filebeat
      register: filebeat_status
    - debug:
      var: filebeat_status.stdout_lines
