---
- name: "service module demo"
  hosts: all
  become: true
  tasks: 
    - name: Restart filebeat 
      service:
       name: "{{ services }}"
       enabled: yes
       state: restarted
    vars:
      services:
       - filebeat
