- name: "service module demo"
  hosts: {{ host }}
  become: true
  tasks: 
    - name: Restart service {{ service }}
      service: name={{ service }} state=restarted enabled=true
    - name: Check the Uptime of the {{ service }}
      shell: "uptime"
      register: Uptime
    - debug: var=Uptime
