- name: "service module demo"
  hosts: ["{{ target }}"]
  become: true
  tasks: 
    - name: Restart service {{ service }}
      service: name={{ service }} state=restarted enabled=true
     shell: sudo service {{ service }} status
     ignore_errors: true
     register: servicestatus

   - name: Show {{ service }} status
     debug:
      msg: '{{ service }} exists.'
     when: servicestatus.rc | int == 0 
