- name: "service module demo"
  hosts: all
  become: true
  tasks: 
    - name: Restart service filebeat {{ service }}
      service: name={{ service}} state=restarted enabled=true
      register: service_status
    - name: debug
      var: service_status.stdout.lines
