- name: "service module demo"
  hosts: all
  become: true
  tasks: 
    - name: Restart service filebeat {{ service }}
      service: name={{ service }} state=restarted enabled=true
      register: services_state
    - name: debug
      debug:
       var: services_state.stdout_lines
